### ISSUE TITLE
Non-configurable bpe save location

### ISSUE THREAD

**Issue by AaronJThompson** [aiqinxuancai/TiktokenSharp#1]
Currently, the BPE is saved to AppContext.BaseDirectory, which is not ideal if usage application are placed in privileged paths and users are trying to run under-privileged. It would be great if this was configurable

**Comment by aiqinxuancai** [comment]
Thank you, I have added the configuration of the **TikToken.PBEFileDirectory** path in commit e9690c69f4600b47ba4a7e45b1f1ea680baa2131. It needs to be set before **TikToken.EncodingForModel()**.

This change has been synced to nuget version 1.0.2.

**Comment by hk-exec** [comment]
I am using it in Azure App Service (Windows). I am doing this before using 
            **TikToken.PBEFileDirectory = Path.Combine(Environment.ContentRootPath)**
before **TikToken.EncodingForModel(modelName)**

On execution, it is throwing the error "Could not find file 'D:\home\site\wwwroot\cl100k_base.tiktoken'." I concluded that it is unable to create the required BEF file in Environment.ContentRootPath. 

NuGet version 1.0.4

For this, I have created a new issue https://github.com/aiqinxuancai/TiktokenSharp/issues/5

Please help.
