### ISSUE TITLE
Getting Error For gpt-3.5-turbo-16k

### ISSUE THREAD

**Issue by sallahbaksh** [aiqinxuancai/TiktokenSharp#12]
Is gpt-3.5-turbo-16k supported? I get an error when I try to do
TikToken tikToken = TikToken.EncodingForModel("gpt-3.5-turbo-16k");

**Comment by paulofloresjunior** [comment]
I think the latest version in Nuget is not the latest one.

**Comment by aiqinxuancai** [comment]
Because the recent OpenAI models use the "cl100k_base" encoder, you can use TikToken.GetEncoding("cl100k_base"); to obtain the encoder for "gpt-3.5-turbo-16k".

**Comment by aiqinxuancai** [comment]
> I think the latest version in Nuget is not the latest one.

Indeed, I have updated the version, the current version is 1.0.7.

**Comment by paulofloresjunior** [comment]
Thank you very much!
