### ISSUE TITLE
TikToken.EncodingForModel causes "Could not find file 'C:\home\site\wwwroot\bpe'" error

### ISSUE THREAD

**Issue by SethSikoia** [aiqinxuancai/TiktokenSharp#13]
I am using the TikToken library within my service to do some encoding using the provided **EncodingForModel**  method, however I encounter some errors related to the a file , 'C:\home\site\wwwroot\bpe', not being found. 

This issue is only reproduced in an azure app service and does not surface when I run the service locally. 

I am using the latest version of 1.0.7 after also testing and reproducing the same error in version 1.0.6. 

` var tikToken = TikToken.EncodingForModel("gpt-3.5-turbo");
 var tokens = tikToken.Encode(promptBuilder.ToString());`

**Comment by aiqinxuancai** [comment]
Hello, I am unable to read and write local directories in this situation. Please download the PBE file and package it along with the code files for distribution. The specific methods are described in the [README](https://github.com/aiqinxuancai/TiktokenSharp#getting-started).
