### ISSUE TITLE
Problem when used in a project that is dockerized with .net 8

### ISSUE THREAD

**Issue by JohnGalt1717** [aiqinxuancai/TiktokenSharp#14]
.net 8 docker containers don't run as admin and have no ability to create folders etc.  TikTokenSharp creates a "bpe" folder under the app folder.  As a result, it causes errors and the only way to address is to use a custom dockerfile that creates this folder during containerization.

It would be nice, if this project used the temp folder instead which is available in the System.IO.Path namespace as this would solve the deployment issue.

**Comment by aiqinxuancai** [comment]
Using a temp folder is indeed a good solution. I will add in the next update.
