### ISSUE TITLE
suggestion: support GetEncoding by encoding name (not just model name)

### ISSUE THREAD

**Issue by jzhouw** [aiqinxuancai/TiktokenSharp#3]
Since gpt3.5 and gpt4 or future models use "cl100k_base", it's more convenient to have a method by encoding name instead of model name.  

references:
SharpToken has a method of GetEncoding(encodingName) https://github.com/dmitry-brazhenko/SharpToken

https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb

**Comment by aiqinxuancai** [comment]
I have added the TikToken.GetEncoding(encodingName) method. 
ecb3b02c9d99d9e034cb53c0aa7e820834e544f8
nuget version 1.0.4
