### ISSUE TITLE
Unable to create "cl100k_base.tiktoken" file at configured location in Azure App Service (Windows)

### ISSUE THREAD

**Issue by hk-exec** [aiqinxuancai/TiktokenSharp#5]
I am using it in Azure App Services (Windows). I am doing this before using 
            **TikToken.PBEFileDirectory = Path.Combine(Environment.ContentRootPath)**
before **TikToken.EncodingForModel(modelName)**

On execution, it is throwing the error "Could not find file 'D:\home\site\wwwroot\cl100k_base.tiktoken'." I concluded that it is unable to create the required BEF file in Environment.ContentRootPath or any location while running in Azure App Services. 

NuGet version 1.0.4

Please help.

**Comment by aiqinxuancai** [comment]
I'm sorry, I haven't used Azure App Services before. This kind of function computation might not be able to read and write locally. You can try placing the cl100k_base.tiktoken file in the same directory as your program when submitting your code, and set `TikToken.PBEFileDirectory = AppContext.BaseDirectory` to see if it works.

**Comment by hk-exec** [comment]
Thanks, @aiqinxuancai.
I have made .tiktoken files part of the code repository. And it worked.
