### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by HavenDV** [aiqinxuancai/TiktokenSharp#6]
Hello.

Your library seems to be the best for token counting. I used it in the provider's OpenAI implementation in our attempt to implement a C# version of LangChain: https://github.com/tryAGI/LangChain

Can I help you a little with the project?

We are using these TargetFramework: `net4.6.2;netstandard2.0;net6.0;net7.0` and some of them give a warning
```
CS1685: The predefined type 'RuntimeHelpers' is defined in multiple assemblies in the global alias.
```

I think you need to define additional TargetFrameworks:
net4.6.2 - to provide support for the .Net Framework starting from the minimum version. If using the netstandard2.0 version of your library, the consumer must have net4.7.2+ due to some issues with the .Net Standard implementation - https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0
<img width="812" alt="image" src="https://github.com/aiqinxuancai/TiktokenSharp/assets/3002068/9066cfab-066c-442e-891e-3e938dd0d066">

net6.0 and net7.0 will give you much better code analyzers and additional diagnostics. Apart from that, it will open the way for optimizations for these TargetFrameworks via #ifdef

There are also many possible improvements in terms of using Spans/Memory to implement allocation-free operations.

**Comment by aiqinxuancai** [comment]
Hello, I tested using .NetFramework4.6.1, the lowest implementation version of .NetStandard2.0, and the result looks normal.
Also, I saw that your project used `net4.6.2;netstandard2.0;net6.0;net7.0` as target, I think net4.6.2 and net6.0;net7.0 are a bit redundant, because these already have netstandard2.0 implementation.
In fact, you only need to keep target as netstandard2.0, so that net4.6.2, net6.0, net7.0 projects can directly install your library in Nuget.

**Comment by HavenDV** [comment]
Ok, that's what I thought at first too.

There is also a problem with your published NuGet package being built in Debug mode.

**Comment by HavenDV** [comment]
I decided to start my implementation based on yours. I will be glad if you join and help in the future if you have any ideas. In any case, you can take a look and learn something new for yourself.
At the moment, I have accelerated the library by a further two times in terms of CPU and 3 times in terms of memory usage, but I am sure that this is far from the limit.
Thank you again for your work, I have listed you in the license and in the list of authors on NuGet
https://github.com/tryAGI/Tiktoken

**Comment by HavenDV** [comment]
I got a little carried away and sped up the code by about 4 times in CPU and 4-5 times in memory in net7.0.
