### ISSUE TITLE
Remove external connections.

### ISSUE THREAD

**Issue by wrharper-AASP** [aiqinxuancai/TiktokenSharp#7]
Why does this require a connection to openaipublic.blob.core.windows.net and how do I remove it?

**Comment by aiqinxuancai** [comment]
There is an instruction in the readme that states that files required for encoding need to be downloaded. If you package the files together during deployment, downloading will not be triggered. The details are explained in the readme.

**Comment by wrharper-AASP** [comment]
i see, it's for the cl100k_base.tiktoken file. thanks
