### ISSUE TITLE
Inaccurate counts

### ISSUE THREAD

**Issue by wrharper-AASP** [aiqinxuancai/TiktokenSharp#8]
The way HTTPClient must do PostAsJsonAsync is different than any standard serializer. Anyone have thoughts on how I can calculate this? Luckily, since it is a positive offset, I can just let it be a little inaccurate, but it would be better to get 100% use out of the tokens.

Total Tokens Count Microsoft: 169
Total Tokens Count Newtonsoft: 169
Total Tokens Count OpenAI: 154

string json = JsonSerializer.Serialize(messages);
json = json.Replace("\r\n", "\n");
string json2 = NJ.JsonConvert.SerializeObject(messages);
json2 = json2.Replace("\r\n", "\n");

Total Tokens Count Microsoft: 169
Total Tokens Count Newtonsoft: 169

Array instead of list:
Total Tokens Count Microsoft: 169
Total Tokens Count Newtonsoft: 169

**Comment by wrharper-AASP** [comment]
I am using TS.TikToken tikToken = TS.TikToken.GetEncoding("cl100k_base"); with 3.5 turbo

**Comment by aiqinxuancai** [comment]
Sorry, I can't see the relevance to this library from your description.

**Comment by wrharper-AASP** [comment]
Do you know where I could report this?
